const services =[
    {id:1, icon: '../icons/regular-check.png', 
        title: 'Periodic check up', 
        slug: 'periodic-check-up', 
        image:'../images/services/periodic-check.webp', 
        description: 'Dental cleanings are essential for maintaining optimal oral health and function. These preventive visits can help stop dental issues before they get worse.'
    },
    {id:2, icon: '../icons/scaling.png', 
        title: 'Scaling and Root Planing', 
        slug: 'scaling-and-root-planing', 
        image:'../images/services/scaling.webp', 
        description: 'Tooth scaling and root planing are nonsurgical deep-cleaning treatments for periodontitis. This severe gum disease can cause you to lose teeth, gums and bone.',
    },
    {id:3, icon: '../icons/filling.png', 
        title: 'Tooth Filing', 
        slug: 'tooth-filing', 
        image:'../images/services/tooth-filing.webp', 
        description: 'Dental fillings are single or combinations of metals, plastics, glass or other materials used to repair or restore teeth. Popular questions about fillings are answered.',
    },
    {id:4, icon: '../icons/bleaching.png', 
        title: 'Bleaching', 
        slug: 'bleaching', 
        image:'../images/services/bleaching.webp', 
        description: 'Teeth whitening is the most popular elective dental treatment on the market. Discoloration can occur for a number of reasons and may be extrinsic or intrinsic.',
    },
    {id:5, icon: '../icons/covering.png', 
        title: 'Covering of Tooth', 
        slug: 'covering-tooth', 
        image:'../images/services/covering.webp', 
        description: 'Dental crowns are permanent caps placed on weak or damaged teeth to protect and cover a tooth. They can be made of materials like metal, ceramic or porcelain.',
    },
    {id:6, icon: '../icons/rct.png', 
        title: 'Root Canal Treatment (RCT)', 
        slug: 'rct', 
        image:'../images/services/rct.webp', 
        description: 'Root canal therapy/treatment (RCT) is used to treat an infected or abscessed tooth. It eliminates infection by removing the nerves and tissues inside of a tooth.',
    },
    {id:7, icon: '../icons/extraction.png', 
        title: 'Tooth Extraction', 
        slug: 'tooth-extraction', 
        image:'../images/services/tooth-extration.webp', 
        description: 'A tooth extraction may be necessary for many reasons, including severe damage or decay. One of the most common dental procedures, a tooth extraction can eliminate bacteria.',
    },
    {id:8, icon: '../icons/implants.png', 
        title: 'Implants', 
        slug: 'implants', 
        image:'../images/services/implants.webp', 
        description: 'A titanium screw (like a tooth root ) that is surgically positioned into the jawbone beneath the gum line. A natural tooth colored crown is then placed over the Dental Implant.',
    },
    {id:9, icon: '', 
        title: 'Orthodontic Treatment', 
        slug: 'orthodontic-treatment', 
        image:'../images/services/orthodontic.jpg', 
        description: 'Orthodontics is a dental specialty focused on aligning your bite. Orthodontic treatments include traditional braces, clear aligners and removable retainers.',
    },
]

export default services